hydra:
  run:
    dir: ./

train_file:
dev_file:
test_file:

# Model
model:
  _target_: models.roberta_baseline.RobertaForMultipleChoiceForZeroShot.from_pretrained

# Data loading
read_tensor:
  _target_: data.reclor_sentence_prefix.convert_examples_into_features
  max_seq_length: 256
  num_workers: 2
  token_num: 5

extended_vocab: ${read_tensor.token_num}

# Data collator
collator:
  _target_: data.collators.ReClorSentenceCollator

# Dataloader
num_workers: 4
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: experiments/roberta.large.wiki_erica_path_v7_v8.2.2.1aug.ctx.1k.2080Ti/checkpoint-500
pretrain:

output_dir:


do_train: True
evaluate_during_training: True

do_eval: True
eval_sub_path:

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
learning_rate: 1.5e-5
gradient_accumulation_steps: 12
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 0.0
num_train_epochs: 10
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0


logging_steps: 5
save_steps: -1
save_best: True
eval_steps: 100
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:

# fairscale.FullyShardedDP
fairscale_config:
  _target_: general_util.fsdp_utils.default_initialize
  fp16: ${fp16}
  reshard_after_forward: False
  cpu_offload: False
  move_grads_to_cpu: False
  move_params_to_cpu: False

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
  outputs_index_or_keys:

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
